### ISSUE TITLE
Allow to skip `localesPath` when `locales` are present

### ISSUE THREAD

**Issue by gabrielfernandes-codes** [beliven-it/fastify-polyglot#7]
Is there any nice way we could skip the `localesPath` to look at the default path in case we only use `locales` parameter? The reason for that is that I get an error on every server boot, as I don't have the `./locales` directory. Would maybe allowing a `null` value for `localesPath` be used to just avoid `getLocales` being called?

**Comment by zuck** [comment]
Hi @fernandesGabriel , it should be fixed with [2078ce7](https://github.com/beliven-it/fastify-polyglot/commit/2078ce79ff793c28711ea47ffb6382c5bfe384c0). It will only log a warning now.
